{
 "current_room": "starting",
 "objects": [
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "roomScam",
   "visible": true,
   "x": -16.30483967372331,
   "y": -18.07218161059315,
   "z": 7.648539833909864
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "portalgate",
   "class_name": "MazePortalGate",
   "facing": 2,
   "locked": false,
   "name": "MazePortalGate_7fe29bd58d30",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 27.935871472302914,
   "y": 3.0,
   "y_sort": false,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "debris",
   "class_name": "MazeBlockage",
   "facing": 2,
   "locked": false,
   "name": "MazeBlockage_7fa9d67fd828",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -5.5,
   "y": 1.5,
   "y_sort": false,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "lock",
   "class_name": "MazeLock",
   "facing": 2,
   "locked": false,
   "name": "cavelock2",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 15.5,
   "y": 1.5,
   "y_sort": false,
   "z": 0.1
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "southBcam",
   "visible": true,
   "x": 4.804288025292883,
   "y": -22.311180826149485,
   "z": 11.429005565617334
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "outsidemark",
   "visible": true,
   "x": 36.9583382428158,
   "y": 17.309507478071787,
   "z": 0.0
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "portalcam",
   "visible": true,
   "x": 18.824760089659534,
   "y": 4.0,
   "z": 16.0
  },
  {
   "art_src": "trigger_default",
   "class_name": "WarpTrigger",
   "destination_marker_name": "ruinswarp",
   "destination_room": null,
   "locked": false,
   "name": "Ttown2ruins",
   "use_marker_room": true,
   "visible": true,
   "x": -59.0,
   "y": -4.0,
   "z": 0.1
  },
  {
   "class_name": "ObjectSpawner",
   "destroy_on_room_exit": false,
   "locked": false,
   "name": "critterspawner1",
   "spawn_class_name": "MazeCritter",
   "spawn_obj_name": "critter1",
   "times_to_fire": 1,
   "visible": true,
   "x": -44.97214883980052,
   "y": 9.097588892218281,
   "z": 0.0
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "portalBG",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "portalBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 26.0,
   "y": 2.5,
   "y_sort": false,
   "z": 0.0
  },
  {
   "art_src": "trigger_default",
   "class_name": "WarpTrigger",
   "destination_marker_name": null,
   "destination_room": "southroom",
   "locked": true,
   "name": "Tstart2southA",
   "use_marker_room": true,
   "visible": false,
   "x": -16.0,
   "y": -13.0,
   "z": 0.0
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "room2cam",
   "visible": true,
   "x": -44.10279257082698,
   "y": 4.0,
   "z": 17.070995359986807
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "southBG2",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "southBbg",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 5.0,
   "y": -21.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "key",
   "class_name": "MazeKey",
   "facing": 2,
   "locked": false,
   "name": "Key_7fd8adf627f0",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 8.777778158585237,
   "y": -1.355555555555556,
   "y_sort": false,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "player",
   "class_name": "MazePlayer",
   "facing": 0,
   "locked": false,
   "name": "MazePlayer_7f81aab05b00",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -13.720640023117276,
   "y": 7.84194180651748,
   "y_sort": false,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "artifact",
   "class_name": "MazePortalKey",
   "facing": 2,
   "locked": false,
   "name": "MazePortalKey_7fe29bd582b0",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 13.484212242598092,
   "y": 43.3337562944558,
   "y_sort": false,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "bg1",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "startBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -4.0,
   "y": 4.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "seacam",
   "visible": true,
   "x": 14.373101157977933,
   "y": 32.867089627789134,
   "z": 16.0
  },
  {
   "art_src": "trigger_default",
   "class_name": "WarpTrigger",
   "destination_marker_name": null,
   "destination_room": "southroomB",
   "locked": true,
   "name": "Tstart2southC",
   "use_marker_room": true,
   "visible": false,
   "x": 11.0,
   "y": -13.0,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "bg2",
   "class_name": "StaticTileBG",
   "facing": 3,
   "locked": false,
   "name": "otherBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -44.0,
   "y": 4.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "ax",
   "class_name": "MazeAx",
   "facing": 2,
   "locked": false,
   "name": "ax",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -16.761627482972933,
   "y": -17.827853254787698,
   "y_sort": false,
   "z": 0.1
  },
  {
   "art_src": "trigger_default",
   "class_name": "WarpTrigger",
   "destination_marker_name": null,
   "destination_room": "southroomB",
   "locked": true,
   "name": "Tstart2southB",
   "use_marker_room": true,
   "visible": false,
   "x": -0.0,
   "y": -13.0,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "seaBG",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "seaBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": 15.0,
   "y": 34.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "bg3",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "southBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -16.0,
   "y": -19.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "ruinscam",
   "visible": true,
   "x": -54.0788068588908,
   "y": -25.46569798795009,
   "z": 10.869957460577599
  },
  {
   "art_src": "trigger_default",
   "class_name": "WarpTrigger",
   "destination_marker_name": "outsidemark",
   "destination_room": null,
   "locked": false,
   "name": "Tportal2outside",
   "use_marker_room": true,
   "visible": true,
   "x": 28.0,
   "y": 3.0,
   "z": 0.1
  },
  {
   "class_name": "ObjectSpawner",
   "destroy_on_room_exit": false,
   "locked": false,
   "name": "critterspawner2",
   "spawn_class_name": "MazeCritter",
   "spawn_obj_name": "critter2",
   "times_to_fire": 1,
   "visible": true,
   "x": -40.470533543010404,
   "y": 1.9088724381474433,
   "z": 0.1
  },
  {
   "bg_color_a": 0,
   "bg_color_b": 0,
   "bg_color_g": 0,
   "bg_color_r": 0,
   "camera_x": -4.0,
   "camera_y": 4.0,
   "camera_z": 16.0,
   "class_name": "WorldPropertiesObject",
   "collision_enabled": true,
   "draw_hud": true,
   "globals_object_class_name": "WorldGlobalsObject",
   "gravity_x": 0.0,
   "gravity_y": 0.0,
   "gravity_z": 0.0,
   "hud_class_name": "MazeHUD",
   "object_grid_snap": true,
   "player_camera_lock": false,
   "room_camera_changes_enabled": true,
   "show_all_rooms": false,
   "show_bounds_all": false,
   "show_collision_all": false,
   "show_origin_all": false
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "room1cam",
   "visible": true,
   "x": -4.0,
   "y": 4.0,
   "z": 16.0
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "debris",
   "class_name": "MazeBlockage",
   "facing": 2,
   "locked": false,
   "name": "southblockage",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -16.5,
   "y": -12.5,
   "y_sort": false,
   "z": 0.1
  },
  {
   "class_name": "LocationMarker",
   "locked": false,
   "name": "ruinswarp",
   "visible": true,
   "x": -59.5,
   "y": -26.5,
   "z": 0.1
  },
  {
   "alpha": 1.0,
   "animating": false,
   "art_off_pct_x": 0.5,
   "art_off_pct_y": 0.5,
   "art_src": "ruinBG",
   "class_name": "StaticTileBG",
   "facing": 2,
   "locked": false,
   "name": "ruinsBG",
   "scale_x": 1.0,
   "scale_y": 1.0,
   "state": "stand",
   "visible": true,
   "x": -46.0,
   "y": -26.0,
   "y_sort": false,
   "z": 0.0
  },
  {
   "can_play": true,
   "class_name": "SoundBlaster",
   "locked": false,
   "name": "SoundBlaster_7fa0ec7e3a58",
   "play_on_room_enter": true,
   "sound_name": "testamb",
   "visible": true,
   "x": 9.185406956013711,
   "y": -26.05735487265739,
   "z": 0.1
  }
 ],
 "rooms": [
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": true,
   "camera_marker_name": "",
   "class_name": "OutsideRoom",
   "left_edge_warp_dest_name": "",
   "name": "outside",
   "objects": [
    "southBbg",
    "southBG",
    "ruinsBG",
    "portalBG",
    "startBG",
    "seaBG",
    "outsidemark",
    "otherBG"
   ],
   "right_edge_warp_dest_name": "",
   "top_edge_warp_dest_name": "",
   "warp_edge_bounds_obj_name": ""
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": false,
   "camera_marker_name": "room1cam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "tha_next",
   "name": "starting",
   "objects": [
    "Tstart2southB",
    "Tstart2southA",
    "MazeBlockage_7fa9d67fd828",
    "cavelock2",
    "southblockage",
    "startBG",
    "Tstart2southC"
   ],
   "right_edge_warp_dest_name": "portalroom",
   "top_edge_warp_dest_name": "sea",
   "warp_edge_bounds_obj_name": "startBG"
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": false,
   "camera_marker_name": "portalcam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "starting",
   "name": "portalroom",
   "objects": [
    "Tportal2outside",
    "portalcam",
    "portalBG",
    "MazePortalGate_7fe29bd58d30"
   ],
   "right_edge_warp_dest_name": "",
   "top_edge_warp_dest_name": "",
   "warp_edge_bounds_obj_name": "portalBG"
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": false,
   "camera_marker_name": "roomScam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "ruins",
   "name": "southroom",
   "objects": [
    "roomScam",
    "southblockage",
    "southBG"
   ],
   "right_edge_warp_dest_name": "",
   "top_edge_warp_dest_name": "starting",
   "warp_edge_bounds_obj_name": "southBG"
  },
  {
   "bottom_edge_warp_dest_name": "starting",
   "camera_follow_player": false,
   "camera_marker_name": "seacam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "",
   "name": "sea",
   "objects": [
    "seaBG",
    "seacam"
   ],
   "right_edge_warp_dest_name": "",
   "top_edge_warp_dest_name": "",
   "warp_edge_bounds_obj_name": "seaBG"
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": false,
   "camera_marker_name": "southBcam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "",
   "name": "southroomB",
   "objects": [
    "southBbg",
    "southBcam",
    "SoundBlaster_7fa0ec7e3a58"
   ],
   "right_edge_warp_dest_name": "",
   "top_edge_warp_dest_name": "starting",
   "warp_edge_bounds_obj_name": "southBbg"
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": false,
   "camera_marker_name": "room2cam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "",
   "name": "tha_next",
   "objects": [
    "critterspawner2",
    "critterspawner1",
    "Ttown2ruins",
    "room2cam",
    "otherBG"
   ],
   "right_edge_warp_dest_name": "starting",
   "top_edge_warp_dest_name": "",
   "warp_edge_bounds_obj_name": "otherBG"
  },
  {
   "bottom_edge_warp_dest_name": "",
   "camera_follow_player": true,
   "camera_marker_name": "ruinscam",
   "class_name": "GameRoom",
   "left_edge_warp_dest_name": "",
   "name": "ruins",
   "objects": [
    "ruinsBG",
    "ruinscam",
    "ruinswarp"
   ],
   "right_edge_warp_dest_name": "southroom",
   "top_edge_warp_dest_name": "",
   "warp_edge_bounds_obj_name": "ruinsBG"
  }
 ]
}